# Generated by Django 3.0.4 on 2020-05-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200519_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pamt',
        ),
    ]
