# Generated by Django 3.0.4 on 2020-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orders_pamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pamt',
            field=models.CharField(default='', max_length=90),
        ),
    ]
